name: Release Solver

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm dpkg cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCPACK_GENERATOR="DEB;RPM"

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver built from lab06 with DEB and RPM packages
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SUPER_TOKEN }}

      - name: Upload DEB
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/*.deb
          asset_name: solver_${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/*.rpm
          asset_name: solver_${{ github.ref_name }}.rpm
          asset_content_type: application/x-rpm
