name: Release Solver

on:
  push:
    tags:
      - 'v*.*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm dpkg cmake build-essential

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install wix -y

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd build
          cpack -G WIX

      - name: Package (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd build
          cpack -G DragNDrop

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifacts
          path: build/*.*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver packaged for all platforms (DEB, RPM, MSI, DMG)
          files: artifacts/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
