name: Release Solver

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm dpkg cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCPACK_GENERATOR="DEB;RPM"

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Upload assets to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver built from lab06 with DEB and RPM packages
          files: |
            build/*.deb
            build/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NAME }}
